repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
    stages: [commit]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.25.0
    hooks:
      - id: terraform_fmt
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        files: \.(py)$
        exclude: ^tests/
        args: [--rcfile=.pylintrc]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: \.(sh)$
      - id: makefile-lint
        name: makefile-lint
        entry: make
        language: system
        files: Makefile
        args: [lint]
