repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: .+  # Check YAML files in all directories
      - id: check-ast
        files: .+  # Check AST (Abstract Syntax Tree) of files in all directories
      - id: end-of-file-fixer
        files: .+  # Check all files for end-of-file issues
      - id: check-added-large-files
        files: .+  # Check all files for large additions
      - id: detect-private-key
        files: .+  # Check all files for private keys
      - id: trailing-whitespace
        files: .+  # Check all files for trailing whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: .+\.py$  # Check Python files in all directories

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: .+\.py$  # Format Python files in all directories

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
        files: .+Dockerfile$  # Lint Dockerfiles in all directories
